pipeline {
    //agent {
    //   docker {
    //        image 'maven:3-alpine' 
    //        args '-v /root/.m2:/root/.m2' 
    //    }
    //}
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Rename artifact'){
            steps {
                //sh "NEWNAME=`date +'%Y_%m_%d_%H_%M_%S_%N'`_`git rev-parse --short HEAD`.jar"
                sh "mv target/java-archive-1.0-SNAPSHOT.jar `date +'%Y_%m_%d_%H_%M_%S_%N'`_`git rev-parse --short HEAD`.jar"
                sh 'ls -lah target'
            }
        }
    }
}
