---
  
- name: Add repository
  yum_repository:
    name: Jenkins
    description: Jenkins repo
    baseurl: http://pkg.jenkins.io/redhat
    gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
    gpgcheck: yes

- name: Install Jenkins
  yum: 
    name: jenkins
    update_cache: yes
    state: present

- name: Start Jenkins
  service:
    name: jenkins
    state: started