---

- name: Add the user jenkins
  user:
    name: jenkins
    password: password
    home: "/var/lib/jenkins"

- name: Copy a "sudoers" file on the remote machine for editing
  copy:
    src: "{{ansible_user_dir}}/.ssh"
    dest: "/var/lib/jenkins/.ssh"
    remote_src: yes