---

- name: Install Jenkins
  yum: 
    name: maven
    update_cache: yes
    state: present

- name: Add the user jenkins
  user:
    name: jenkins
    password: password
    home: "/var/lib/jenkins"

- name: Set authorized key taken from file
  authorized_key:
    user: jenkins
    state: present
    key: "{{ lookup('file', '~/.ssh/authorized_keys') }}"